kind: pipeline
name: default

platform:
    os: linux
    arch: amd64

steps:
    - name: build_test
      image: node:10
      environment:
          GITHUB_TOKEN:
              from_secret: GITHUB_TOKEN
      commands:
          - npm install --unsafe-perm
          - npm link --unsafe-perm
          - npm run lint
          - npm test
